

name: CI
on: 
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install pytest pytest-cov
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize database
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          python -c "from database import init_database, add_sample_data; init_database(); add_sample_data()"

      - name: Run tests with coverage
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest --cov=library_service --cov=database --cov-report=xml tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}